name: 'FOSSA Action'

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Install npm packages
        run: corepack enable && yarn --immutable

      - name: Run lint
        run: yarn lint

